---
# This is a dummy file for testing out the home assistant & esp home configuration
# It goes without saying, these are not my actual secrets....

# ESPHome (generic)
esphome_api_password: password
esphome_ota_password: password
esphome_web_server_password: password

# Home Assistant
home_name: Betty
home_latitude: 0
home_longitude: 0
home_elevation: 100
home_time_zone: Europe/London
ha_remote_base: http://127.0.0.1:8123
ha_local_base: http://127.0.0.1:8123
