---
# This is a dummy file for testing out the home assistant & esp home configuration
# It goes without saying, these are not my actual secrets....

# ESPHome (generic)
esphome_api_password: password
esphome_ota_password: password
esphome_web_server_password: password

# Home Assistant
home_name: Betty
home_latitude: 0
home_longitude: 0
home_elevation: 100
home_time_zone: Europe/London
ha_remote_base: http://127.0.0.1:8123
ha_local_base: http://127.0.0.1:8123


#######################################################################################
# SONOS IP ADDRESSES                                                                  #
#######################################################################################
sonos_office_ip_address: 192.168.1.2
sonos_arc_ip_address: 192.168.1.3
sonos_mbed_1_ip_address: 192.168.1.4
sonos_mbed_2_ip_address: 192.168.1.5
sonos_move_ip_address: 192.168.1.6
sonos_roam_ip_address: 192.168.1.7
sonos_mbath_ip_address: 192.168.1.8
sonos_kitchen_ip_address: 192.168.1.9

#######################################################################################
# SONOS IP ADDRESSES                                                                  #
#######################################################################################
duckdns_domain: not_real
duckdns_access_token: token_xxx
