---
# Bug report for GitHub
#
# Template for creating a new bug within the my-smart-home repo
#
name: 🐞 Bug
description: File a bug/issue
title: "[Bug]: <title>"
labels: ["bug", "triage"]
assignees:
  - ZinkNotTheMetal
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Has this happened before?
      options:
        - label: Yes?
          required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References?
        Anything that will give me more context about the issue you are encountering!

        Tip: You can attach files by clicking this area to highlight it
         and then dragging files in.
