---
# Home Assistant configuration
#
# Template for creating a new Automation within the my-smart-home repo
#
# Reference Documentation
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax

# https://www.home-assistant.io/integrations/api/
api:
# https://www.home-assistant.io/integrations/default_config/
# Loads default set of integrations. Do NOT remove.
default_config:

homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  time_zone: !secret home_time_zone
  elevation: !secret home_elevation
  country: US
  language: en
  currency: USD
  unit_system: us_customary

#######################################################################################
# All Sensors that are in Home Assistant
#
# https://www.home-assistant.io/components/sensor
sensor: !include_dir_merge_list integrations/sensors
#######################################################################################

#######################################################################################
# The input_boolean component allows the user to define boolean values that
# can be controlled via the frontend and can be used within conditions of
# automation. This can for example be used to disable or enable certain
# automations.
#
# https://www.home-assistant.io/components/input_boolean/
input_boolean: !include_dir_merge_named components/input_booleans
#######################################################################################

#######################################################################################
# SONOS Manual - Auto Discovery not working with multiple VLANs
#
# https://www.home-assistant.io/integrations/sonos/
sonos:
  media_player:
    hosts:
      - !secret sonos_office_ip_address
      - !secret sonos_arc_ip_address
      - !secret sonos_mbed_1_ip_address
      - !secret sonos_mbed_2_ip_address
      - !secret sonos_move_ip_address
      - !secret sonos_roam_ip_address
      - !secret sonos_mbath_ip_address
      - !secret sonos_kitchen_ip_address
#######################################################################################

#######################################################################################
# SWAG Configuration (reverse proxy)
#
# https://www.home-assistant.io/integrations/http/
http:
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  trusted_proxies:
    - 192.168.86.0/24
    - 172.16.0.0/12
#######################################################################################

#######################################################################################
# DuckDNS (dynamic DNS) - custom URL
#
# https://www.home-assistant.io/integrations/duckdns
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token
#######################################################################################
