---
# Home Assistant configuration
#
# Template for creating a new Automation within the my-smart-home repo
#
# Reference Documentation
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax

# https://www.home-assistant.io/integrations/api/
api:
# https://www.home-assistant.io/integrations/default_config/
# Loads default set of integrations. Do NOT remove.
default_config:

homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  time_zone: !secret home_time_zone
  elevation: !secret home_elevation
  country: US
  language: en
  currency: USD
  unit_system: us_customary
  # Packages #
  packages: !include_dir_named integrations
