name: Home Assistant CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3.5.3
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use present-lint-recommended ."