#############################################################
#                                                           #
#         Sensor Templates                                  #
# https://www.home-assistant.io/integrations/template/      #
#                                                           #
#############################################################
- platform: template
  sensors:
    sensor_count:
      friendly_name: 'Number of Sensors'
      value_template: >
        {%- set domains = ['sensor'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    lights_count:
      friendly_name: 'Number of Lights'
      value_template: >
        {%- set domains = ['light'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
    back_sliding_glass_door:
      friendly_name: 'Back Sliding Glass Door'
      value_template: >
        {{ is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_opening', 'on') or is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_3', 'on') }}